name: Testing variables
on:
    workflow_dispatch
env:
    place: "Inside the workflow"

jobs:
    job_1:
        runs-on: ubuntu-latest
        env:
            place_2: "Udaya"
        steps:
            - name: Print the variable
              run: echo "$place_2 is using the repository variable with project_id ${{ vars.PROJECT_ID }} , secret ${{secrets.SECRET_ID}} inside $place"
